---
name: "Build SPC Project with Maven"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4
      
      - name: "Create Environment"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'tumerin'
          cache: 'maven'

      - name: "Build with Maven"
        run: mvn clean package