---
# Created by AB
# Info: This is for SPC Java based project. Steps -->> Test -> Build -> create Docker Image -> push to ECR

name: Build SPC project and push Docker Image to ECR

on:
  push:
    branches: [ ab-prac ]

jobs:
  build: # First Job
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # - name: Unit Test
      #   run: mvn test

      - name: Build
        run: mvn clean package -Dmaven.test.skip=true

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spc.jar
          path: '**/target/*.jar'

  Docker: # Second Job
    needs: build # Adding dependency for the above 'First Job'

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: spc.jar
          path: ./app

      - name: Find Artifact path # Finding the exact path for the downloaded Artifact
        run: |
          echo "Searching for JAR files..."
          find . -type f -name "*.jar" -print

      - name: Create Docker image
        run: docker image build -t test/pub . # Building the Docker Image as per the ECR Repo

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Secrets stored in the GitHub Repo Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' # AWS Region must be 'us-east-1' for public ECR Repos

      - name: Login to ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v2x6c7f6

      - name: Tag Docker Image # Tag the image to make it ECR comptible (Mandatory step for ECR)
        run: |
          docker tag test/pub:latest public.ecr.aws/v2x6c7f6/test/pub:latest

      - name: Push to ECR
        run: |
          docker push public.ecr.aws/v2x6c7f6/test/pub:latest
        
        