---
# Created By AB

name: Test and Build SPC Project (CI)

on:
  workflow_dispatch: # Run job Manually


jobs:
  build: # First Job name (CI)
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: create environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Uit Tests
        run: mvn test

      - name: Create Package with Maven
        run: mvn clean package -Dmaven.test.skip=true # Skip to run/compile the tests again as we are already running them in above 'test' step

